<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2011 xored software, Inc.
  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License v1.0
  which accompanies this distribution, and is available at
  http://www.eclipse.org/legal/epl-v10.html
  
  Contributors:
      xored software, Inc - initial API and implementation
-->
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="editing"
    nsURI="http://www.eclipse.org/ecl/editing.ecore" nsPrefix="org.eclipse.ecl.editing">
  <eClassifiers xsi:type="ecore:EClass" name="Complete" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proposal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insert" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="display" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ProposalType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProposalType">
    <eLiterals name="CommandName"/>
    <eLiterals name="ParamName" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Doc">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
