<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ccvs"
    nsURI="http://www.eclipse.org/ecl/cc/cvs.ecore" nsPrefix="org.eclipse.ecl.cc.cvs">
  <eClassifiers xsi:type="ecore:EClass" name="GetCVSLocations" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="CVSLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionType" eType="#//CVSConnectionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CVSConnectionType">
    <eLiterals name="pserver"/>
    <eLiterals name="extssh" value="1"/>
    <eLiterals name="ext" value="2"/>
    <eLiterals name="pserverssh2" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddCVSLocations" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//CVSLocation" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
