<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ast"
    nsURI="http://www.eclipse.org/ecl/ast.ecore" nsPrefix="org.eclipse.ecl.ast">
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ast" eType="#//Ast"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partition" eType="#//EclPartition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Node" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EclPartition" instanceClassName="org.eclipse.ecl.parser.EclPartition"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Ast" instanceClassName="org.eclipse.ecl.ast.Ast"/>
</ecore:EPackage>
