<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2011 xored software, Inc.
  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License v1.0
  which accompanies this distribution, and is available at
  http://www.eclipse.org/legal/epl-v10.html
  
  Contributors:
      xored software, Inc - initial API and implementation
-->
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://www.eclipse.org/ecl/tests/model.ecore" nsPrefix="org.eclipse.ecl.core.tests.model">
  <eClassifiers xsi:type="ecore:EClass" name="TestCommand" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hello" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlowCommand" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="IncrementCommand" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmitData" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Random" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsPipeEmpty" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmitEMFData" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fail" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command"/>
</ecore:EPackage>
