<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="operations"
    nsURI="http://www.eclipse.org/ecl/operations.ecore" nsPrefix="org.eclipse.ecl.core">
  <eClassifiers xsi:type="ecore:EClass" name="Eq" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Compares arguments on equality"/>
      <details key="returns" value="&lt;code>true&lt;/code> when args are equal, &lt;code>false&lt;/code> otherwise."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Left argument"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Right argument"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Int" eSuperTypes="#//Convert">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Converts its argument to int."/>
      <details key="returns" value="Returns integer value or fails if value cannot be converted. &lt;code>true&lt;/code> is converted to &lt;code>1&lt;/code> and &lt;code>false&lt;/code> is converted to &lt;code>0&lt;/code>."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bool" eSuperTypes="#//Convert">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Converts its argument to boolean."/>
      <details key="returns" value="Returns boolean value or fails if value cannot be converted. "/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Str" eSuperTypes="#//Convert">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Converts its argument to string."/>
      <details key="returns" value="Returns string value or fails if value cannot be converted. "/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Convert" abstract="true" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/internal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Argument to be converted to string."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssertTrue" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="If input is not true, fails"/>
      <details key="returns" value="Nothing"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Input value. Must be true."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Message to fail with when input is not true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Length" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Returns count of objects got from input pipe"/>
      <details key="returns" value="Object count"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="List of objects to get the length for"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotEq" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Compares arguments are different"/>
      <details key="returns" value="&lt;code>false&lt;/code> when args are equal, &lt;code>true&lt;/code> otherwise."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Left argument"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Right argument"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gt" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Compares arguments on to one be greater then another"/>
      <details key="returns" value="&lt;code>true&lt;/code> when left are greater then right, &lt;code>false&lt;/code> otherwise."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Left argument"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Right argument"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lt" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Compares arguments one are less then another"/>
      <details key="returns" value="&lt;code>true&lt;/code> when left is less then right, &lt;code>false&lt;/code> otherwise."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Left argument"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Right argument"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Return !value"/>
      <details key="returns" value="&lt;code>true&lt;/code> when value is false, &lt;code>false&lt;/code> otherwise."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Left argument"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Try" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Try to execute command, retry times with delay if command are failed.&#xA;Execute catch if all operations is not succesfull. Execute finally in anyway."/>
      <details key="returns" value="return's -command output if command is successed."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" eType="ecore:EClass ../../org.eclipse.ecl.core/model/ecl.ecore#//Command"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catch" eType="ecore:EClass ../../org.eclipse.ecl.core/model/ecl.ecore#//Command"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finally" eType="ecore:EClass ../../org.eclipse.ecl.core/model/ecl.ecore#//Command"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="times" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Format" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Writes a formatted string to output pipe"/>
      <details key="returns" value="Formatted string"/>
      <details key="example" value="format &quot;string: %s, int: %d&quot; &quot;foo&quot; 5 | log"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Format string as in Java's &lt;a href=&quot;http://docs.oracle.com/javase/6/docs/api/java/util/Formatter.html&quot;>String.format&lt;/a>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" unique="false" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/docs">
        <details key="description" value="Arguments for format string"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emit" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Writes its arguments into output pipe. "/>
      <details key="returns" value="List of arguments"/>
      <details key="example" value="emit &quot;hello&quot; &quot;world&quot; | foreach { log }"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" unique="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepeatWith" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Takes list of commands from input pipe and single command as argument and executes them in following order: &#xA;&lt;pre>&#xA;command-from-input-1 | command-from-arg&#xA;command-from-input-2 | command-from-arg&#xA;...&#xA;&lt;/pre>"/>
      <details key="returns" value="Aggregated output of command from argument"/>
      <details key="example" value="// executes commands:&#xA;// echo 1 | gt 2&#xA;// echo 2 | gt 2&#xA;// echo 3 | gt 2&#xA;// output: false, false, true&#xA;emit { echo 1}, { echo 2}, { echo 3} | repeat-with { gt 2 } "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" unique="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/ecl/input"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" eType="ecore:EClass ../../org.eclipse.ecl.core/model/ecl.ecore#//Command"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="../../org.eclipse.ecl.core/model/ecl.ecore#//Command">
    <eAnnotations source="http://www.eclipse.org/ecl/docs">
      <details key="description" value="Execute specified command multiple times."/>
      <details key="returns" value="return's -command output if command is successed."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="times" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ecl.core/model/ecl.ecore#//Command"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
  </eClassifiers>
</ecore:EPackage>
